#
# ansible-playbook -i 127.0.0.1, check-php-no-names.yaml
#
# Compare the output of this playbook to the output of "check-php.yaml"

- hosts: all
  become: yes

  tasks:

  - register: php_installed
    command: php -v
    ignore_errors: true

  - debug: var=php_install
    when: php_installed|success

  - debug: msg='PHP is NOT installed'
    when: php_installed|failed