--- 
- hosts: webservers
  become: true

  vars:
    doc_root: /var/www/example

  tasks: 
    - name: Ensure Apache is installed 
      package: name=httpd state=present

    - name: Ensure document root exists
      file: path={{ doc_root }} state=directory owner=apache group=apache

    - name: Ensure HTML file is installed
      copy: src=index.html dest={{ doc_root }}/index.html owner=apache group=apache

    - name: Ensure Virtual host file is installed from template
      template: src=vhost.template dest=/etc/httpd/conf.d/000-default.conf
      notify: restart apache

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
